- name: create Dashboard File
  ansible.builtin.template:
    src: dashboard.json
    dest: /tmp/dashboard.json

- name: Add Grafana Dashboard
  community.grafana.grafana_dashboard:
    grafana_url: http://172.31.47.42:3000
  #grafana_api_key: "{{ lookup('amazon.aws.aws_ssm", 'grana.api_key', region='us-east-1') }}"
    grafana_api_key: "glsa_XXQZsEAoephWXBod59sioIAG3tLzvZzc_2f5bae2c"
    state: present
    commit_message: updated by ansible
    overwrite: yes
    path: /tmp/dashboard.json
