- name: Create Dashboard File
  ansible.builtin.template:
    src: dashboard.json
    dest: /tmp/dashboard.json

- name: Add Grafana dashboard
  community.grafana.grafana_dashboard:
    grafana_url: http://172.31.32.136:3000
  #grafana_api_key: "{{lookup('amazon.aws.aws_ssm', 'grafana.api_key', region='us_east_1')}}"
    grafana_api_key: "glsa_oAE5roVOzNxpi9Qbm4V15uRkhb3Nu3AX_3d76a6e7"
    state: present
    commit_message: updated by ansible
    overwrite: yes
    path: /tmp/dashboard.json
