- name: Copy Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Copy Alert Rules
  ansible.builtin.template:
    src: common.yml
    dest: /opt/prometheus/alert-rules/common.yml

- name: List All files in Bucket
  amazon.aws.s3_object:
    bucket: sai-prometheus-alert-rules
    mode: list
  register: OUT

- name: Download all the objects from s3 Bucket Having Alert Files
  amazon.aws.s3_object:
    bucket: sai-prometheus-alert-rules
    mode: get
    object: "{{item}}"
    dest: /opt/prometheus/alert-rules/{{item}}
  loop: "{{OUT.s3_keys}}"

